# Generated by Django 5.2.12 on 2026-03-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$o7Ypoz6CJGfWgGT9ujMY4h$ouCSB8rz+82ircI1LBrYBhH6Lfcmbv9T2M1wqxWiJBY=', max_length=255),
        ),
    ]
