# Generated by Django 4.2.7 on 2026-03-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.EmailField(default='temp@local.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$SCELZVhzLE8eljLSuLuwow$I7iY77nNiWBc6E3Ree1U/bBc96VYNbB6/uNEsaEugno=', max_length=255),
        ),
    ]
