# Generated by Django 5.2.12 on 2026-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='temp@local.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$zXFp5HkvKL3kyCadHBfGBa$hpKuNK3ER9niB8sx3jlWMFz0Z43kvpCqp5QF/amxXqw=', max_length=255),
        ),
    ]
