# Generated by Django 4.2.7 on 2026-03-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='replied_by_staff_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, default=''),
        ),
    ]
